# Step 1: Build the application
FROM node:18-slim AS build

WORKDIR /app

# install dependancies
COPY package*.json ./
RUN npm install

# copy the rest of the files and build
COPY . .
RUN npm run build

# Step 2: Serve with NGINX
FROM nginx:alpine

# Copy custom nginx config
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf.d/default.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]